### ISSUE TITLE
Unable to save properties of new OBS instance

### ISSUE THREAD

**Issue by hussra** [bitfocus/companion-module-obs-studio#30]
I've got a fresh CompanionPi install, fully updated and running HEAD. Tried to create an obs-studio instance, but Companion (the whole thing) crashes when saving the instance properties.

Running with some logging added, I got this error:

Starting
Started
/usr/local/src/companion/lib/module/obs-studio/index.js:22
        self.obs.disconnect();
                 ^

TypeError: Cannot read property 'disconnect' of undefined
    at instance.updateConfig (/usr/local/src/companion/lib/module/obs-studio/index.js:22:11)
    at EventEmitter.<anonymous> (/usr/local/src/companion/lib/instance.js:392:21)
    at emitTwo (events.js:126:13)
    at EventEmitter.emit (events.js:214:7)
    at Socket.<anonymous> (/usr/local/src/companion/lib/instance.js:542:15)
    at emitTwo (events.js:126:13)
    at Socket.emit (events.js:214:7)
    at /usr/local/src/companion/node_modules/socket.io/lib/socket.js:528:12
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)

My knowledge of Companion internals is still low, but it looks like we need to check for self.obs being undefined here, for a brand-new obs-studio instance that hasn't yet had its properties saved, I wrapped line 22 in a suitable if (self.obs !== undefined) check, and things are looking a whole lot healthier.

**Comment by tdobes** [comment]
I'm experiencing what I believe to be a problem which possibly has the same root cause.  With the latest version, enabling/disabling an OBS instance results in a crash of Companion.  This is the error:
TypeError: Cannot read property 'destroy' of undefined
    at tcp.<anonymous> (/opt/companion/lib/module/obs-studio/index.js:50:12)
    at emitOne (events.js:116:13)
    at tcp.emit (events.js:211:7)
    at Socket.<anonymous> (/opt/companion/lib/tcp.js:99:8)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1177:10)

After a bit of triage over recent commits, I've discovered that reverting commit c360ce267a9270f45a61b9b47b770525141a68c2 fixes the problem.

**Comment by bryce-seifert** [comment]
Sorry about this, I must have missed that when re-working the disconnect behavior.
Can you please test if this fixes?
https://github.com/bitfocus/companion-module-obs-studio/pull/32

**Comment by tdobes** [comment]
A quick test against the latest HEAD with PR #32 applied appears to work as expected.

**Comment by hussra** [comment]
Likewise, looking good for me with PR #32 applied. Thank you!

**Comment by WaffleTime16** [comment]
Looking good here as well.  Forgive my ignorance, as I'm learning.  With modifications such as these, do they get implemented into the normal software updates for Companion?  I modified the code as instructed, but I'm wondering if (running it on a RPi4) when I go to update companion, will that pull down the new code for this module as well?  

Thanks in advance!

**Comment by eric** [comment]
Can this be closed?

**Comment by hussra** [comment]
I think so.
